/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import javax.swing.*;
import main.GestorConfiguracion;

/**
 *
 * @author andresimery
 */
public class VentanaConfiguracion extends javax.swing.JFrame {
    private static GestorConfiguracion gestor;
    
    /**
     * Creates new form VentanaConfiguracion
     */
    public VentanaConfiguracion() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        gestor = new GestorConfiguracion();
        setup();
        setVisible(true);
    }
    
    private void setup() {
        gestor.cargarDesdeJSON();
        txtNumCPUs.setText(String.valueOf(gestor.getNumCPUs()));
        txtDuracionCiclo.setText(String.valueOf(gestor.getDuracionCiclo()));
        comboAlgoritmo.setSelectedItem(gestor.getAlgoritmoActual());
    }
    
    public void cargarJSON() {
        
    }

    public GestorConfiguracion getGestor() {
        return gestor;
    }

    public void setGestor(GestorConfiguracion gestor) {
        this.gestor = gestor;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNumCPUs = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        jLabelNumeroCpus = new javax.swing.JLabel();
        jLabelDuracionCiclo = new javax.swing.JLabel();
        txtDuracionCiclo = new javax.swing.JTextField();
        comboAlgoritmo = new javax.swing.JComboBox<>();
        jLabelAlgoritmo = new javax.swing.JLabel();
        btnGuardarJSON = new javax.swing.JButton();
        btnGestionarProcesos = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumCPUs.setText("3");
        txtNumCPUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCPUsActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumCPUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 110, 20));

        titulo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Configuración");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabelNumeroCpus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNumeroCpus.setText("Numero CPUs:");
        jPanel1.add(jLabelNumeroCpus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabelDuracionCiclo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDuracionCiclo.setText("Duración Ciclo:");
        jPanel1.add(jLabelDuracionCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        txtDuracionCiclo.setText("500");
        txtDuracionCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionCicloActionPerformed(evt);
            }
        });
        jPanel1.add(txtDuracionCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, 20));

        comboAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "SPN", "HRRN", "SRT", "RR" }));
        jPanel1.add(comboAlgoritmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 110, 20));

        jLabelAlgoritmo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAlgoritmo.setText("Algoritmo:");
        jPanel1.add(jLabelAlgoritmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        btnGuardarJSON.setText("Guardar en JSON");
        btnGuardarJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarJSONActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarJSON, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 160, -1));

        btnGestionarProcesos.setText("Gestión de Procesos");
        btnGestionarProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarProcesosActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionarProcesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, -1));

        btnIniciar.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumCPUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCPUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCPUsActionPerformed

    private void txtDuracionCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionCicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionCicloActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        gestor.setAlgoritmoActual(comboAlgoritmo.getSelectedItem().toString());
        this.setVisible(false);
        new SimuladorInterfaz(gestor);
        this.dispose();
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnGuardarJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarJSONActionPerformed
        int duracionCiclo;
        int numCpus;
        
        try {
            duracionCiclo = Integer.parseInt(txtDuracionCiclo.getText());
            numCpus = Integer.parseInt(txtNumCPUs.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        gestor.setAlgoritmoActual(comboAlgoritmo.getSelectedItem().toString());
        gestor.setDuracionCiclo(duracionCiclo);
        gestor.setNumCPUs(numCpus);
        
        gestor.guardarEnJSON();
    }//GEN-LAST:event_btnGuardarJSONActionPerformed

    private void btnGestionarProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarProcesosActionPerformed
        GestionProcesos gestionProcesos = new GestionProcesos(this);
        this.setVisible(false);
    }//GEN-LAST:event_btnGestionarProcesosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConfiguracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionarProcesos;
    private javax.swing.JButton btnGuardarJSON;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JComboBox<String> comboAlgoritmo;
    private javax.swing.JLabel jLabelAlgoritmo;
    private javax.swing.JLabel jLabelDuracionCiclo;
    private javax.swing.JLabel jLabelNumeroCpus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtDuracionCiclo;
    private javax.swing.JTextField txtNumCPUs;
    // End of variables declaration//GEN-END:variables
}
